// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnjpGF2dlOkF0UDouD1pwaxsbgjE6bRTs',
    appId: '1:914063189191:web:bb2bf2be7e145b9102cae2',
    messagingSenderId: '914063189191',
    projectId: 'minidevblogfecchio',
    authDomain: 'minidevblogfecchio.firebaseapp.com',
    databaseURL: 'https://minidevblogfecchio-default-rtdb.firebaseio.com',
    storageBucket: 'minidevblogfecchio.appspot.com',
    measurementId: 'G-J9069JEZR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClj3LpDqDk-ztJFUzREus18JvussKwHLc',
    appId: '1:914063189191:android:2f2925275d66ac9902cae2',
    messagingSenderId: '914063189191',
    projectId: 'minidevblogfecchio',
    databaseURL: 'https://minidevblogfecchio-default-rtdb.firebaseio.com',
    storageBucket: 'minidevblogfecchio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN939dpgaG7p37kWaHen0lqKQEsNXUuPM',
    appId: '1:914063189191:ios:220495fb8b359e4202cae2',
    messagingSenderId: '914063189191',
    projectId: 'minidevblogfecchio',
    databaseURL: 'https://minidevblogfecchio-default-rtdb.firebaseio.com',
    storageBucket: 'minidevblogfecchio.appspot.com',
    iosBundleId: 'com.example.firebaseTutorialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN939dpgaG7p37kWaHen0lqKQEsNXUuPM',
    appId: '1:914063189191:ios:220495fb8b359e4202cae2',
    messagingSenderId: '914063189191',
    projectId: 'minidevblogfecchio',
    databaseURL: 'https://minidevblogfecchio-default-rtdb.firebaseio.com',
    storageBucket: 'minidevblogfecchio.appspot.com',
    iosBundleId: 'com.example.firebaseTutorialApp',
  );
}
